# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "core.ipynb",
         "HelloSayer": "core.ipynb",
         "load": "core.ipynb",
         "tokenize": "core.ipynb",
         "index": "core.ipynb",
         "TokenFrame": "core.ipynb",
         "IndexFrame": "core.ipynb",
         "match": "core.ipynb",
         "MatchFrame": "core.ipynb",
         "sha2": "util.ipynb",
         "Hash": "util.ipynb"}

modules = ["core.py",
           "util.py"]

doc_url = "https://alfl.github.io/proofzero_sdk/"

git_url = "https://github.com/alfl/proofzero_sdk/tree/main/"

def custom_doc_links(name): return None
