# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://alfl.github.io/proofzero_sdk/"

git_url = "https://github.com/alfl/proofzero_sdk/tree/main/"

def custom_doc_links(name): return None
