# AUTOGENERATED! DO NOT EDIT! File to edit: util.ipynb (unless otherwise specified).

__all__ = ['Hash', 'sha2']

# Cell
from typing import NewType
Hash = NewType('Hash', str)

# Cell
import pandas as pd
def sha2(filename: str) -> pd.DataFrame:
    """
    Convenience function for loading files using `pandas`. Full version supports XLSX, etc.
    """
    return pd.read_csv(filename)